//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dathang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dathang()
        {
            this.CTDathang = new HashSet<CTDathang>();
        }
    
        public int MaPhieuDat { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
        public string TrangThai { get; set; }
        public string DiaChi { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDathang> CTDathang { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
